### ISSUE TITLE
ERROR: invalid or damaged sequence database to be searched by hhblits

### ISSUE THREAD

**Issue by natduran** [j3xugit/RaptorX-3DModeling#7]
Hi everyone! 

I am trying to run the code for the example 1pazA.fasta and I have verified that the UniRef30 database is in the correct path on the file raptorx-external.sh (as suggested on issue #6 )
>  export HHDB=/home/lab/RaptorX-3DModeling/hh-suite-master/databases/UniRef30_2020_03

However, I keep getting the Error as follows: 

> (RaptorX) myname@xxxx:~/RaptorX-3DModeling$ Server/RaptorXFolder.sh -o example/ -g -1 -m 8 -r 1 example/1pazA.fasta
> ERROR: invalid or damaged sequence database to be searched by hhblits: /home/lab/RaptorX-3DModeling/hh-suite-master/databases/UniRef30_2020_03
> ERROR: failed to run /home/lab/RaptorX-3DModeling/BuildFeatures/BuildMSAs.sh -d example/ -m 8 example/1pazA.fasta
> ERROR: failed to run /home/lab/RaptorX-3DModeling/BuildFeatures/BuildFeatures.sh -o example/ -g -1 -m 8 -r 4 example/1pazA.fasta 

Can I get some help please? 

~Nat

**Comment by j3xugit** [comment]
Please set HHDB as follows.

export HHDB=/home/lab/RaptorX-3DModeling/hh-suite-master/databases/UniRef30_2020_03/UniRef30_2020_03

**Comment by natduran** [comment]
Hi @j3xugit !

Thanks for the prompt reply, I did as you advise me and it ran smoothly. However I am getting the following error now: 
> ERROR: the a3m file does not exist: example//1pazA_OUT//1pazA_thread/1pazA.a3m
> ERROR: Failed to collect input feature for property prediction!
> ERROR: failed to run /home/lab/RaptorX-3DModeling/DL4PropertyPrediction//Scripts/PredictProperty4Server.sh -g -1 1pazA example//1pazA_OUT/

How could we solve this? 

~Nat

**Comment by j3xugit** [comment]
Can you email me (jinboxu@gmailcom) your command line and all the screen output?
In  addition, can you also check out the content in example/1pazA_OUT/ ? 
I would like to see what has been generated in this folder.

**Comment by natduran** [comment]
of course, I've just send you the information. 
thank you so much for your support. 

~Nat
